katas/2017-10-25_BerlinClock/solutions/tobi/BerlinClock/Components/ClockSegmentViewComponent.cs
using BerlinClock.Model;
using Microsoft.AspNetCore.Mvc;

namespace BerlinClock.Components
{
    [ViewComponent]
    public class ClockSegmentViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string id, int segmentsNumber, int activeSegmentNumber)
        {
            return View("ClockSegment", new ClockSegmentModel() { Id = id, Segments = segmentsNumber, FilledSegments = activeSegmentNumber });
        }
    }
}

katas/2017-10-25_BerlinClock/solutions/tobi/BerlinClock/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BerlinClock.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

katas/2017-10-25_BerlinClock/solutions/tobi/BerlinClock/Pages/Index.cshtml.cs
using BerlinClock.Controller;
using BerlinClock.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BerlinClock.Pages
{
    public class IndexModel : PageModel
    {
        public const int SecondsToFetch = 5;

        private readonly ILogger<IndexModel> _logger;
        private readonly TimeController _timeController;
        public SegmentModel SegmentData { get; private set; }

        public IndexModel(ILogger<IndexModel> logger, TimeController timeController)
        {
            _logger = logger;
            _timeController = timeController;
        }

        public void OnGet()
        {
            // Simulate Api Call
            SegmentData = _timeController.GetSegmentedTime();
        }
    }
}

katas/2017-10-25_BerlinClock/solutions/tobi/BerlinClock/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BerlinClock.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

katas/2017-10-25_BerlinClock/solutions/tobi/BerlinClock/Pages/Components/ClockSegment/ClockSegment.cshtml
@using BerlinClock.Model
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ClockSegmentModel
@{
}

<div class="clock-segment" id="@Model.Id">
    @{
        var elementWidth = $"{((1 / (double)Model.Segments) * 100.0).ToString().Replace(",", ".")}%";
        for(var i = 0; i < Model.Segments; i++)
        {
            <div class="clock-subsegment @(Model.FilledSegments > i ? "active" : "")" style="width: @elementWidth">
            </div>
        }
     }
</div>

katas/2017-10-25_BerlinClock/solutions/tobi/BerlinClock/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Berlin Clock";
}

<div class="text-center">
    <div class="clock-wrapper">
        @await Component.InvokeAsync("ClockSegment", new { id = "clock-segment-hour-first", segmentsNumber = 4, activeSegmentNumber = @Model.SegmentData.HourSegmentFirst })
        @await Component.InvokeAsync("ClockSegment", new { id = "clock-segment-hour-second", segmentsNumber = 4, activeSegmentNumber = @Model.SegmentData.HourSegmentSecond })
        @await Component.InvokeAsync("ClockSegment", new { id = "clock-segment-minute-first", segmentsNumber = 11, activeSegmentNumber = @Model.SegmentData.MinuteSegmentFirst })
        @await Component.InvokeAsync("ClockSegment", new { id = "clock-segment-minute-second", segmentsNumber = 4, activeSegmentNumber = @Model.SegmentData.MinuteSegmentSecond })
    </div>
</div>

<style>
    .clock-wrapper {
        text-align: center;
        margin: auto;
    }

    .clock-segment {
        width: 500px;
        height: 100px;
        border: 1px solid;
        display: flex;
    }

    .clock-subsegment {
        box-sizing: border-box;
        border: 1px solid;
        height: 100px;
        display: inline-block;
        background-color: #4d5152
    }

    .clock-segment .active {
        background-color: #ff6800
    }
</style>

<script>
    setTimeout("location.reload(true);", (@IndexModel.SecondsToFetch * 1000));
</script>

katas/2017-10-25_BerlinClock/solutions/tobi/BerlinClock/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BerlinClock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BerlinClock.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BerlinClock</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BerlinClock
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>